# -*- coding: utf-8 -*-
"""1_Tokeniszation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bep-s_jKdErBmZJbSSz4fjJJJloZljTE

# **Tokenizing Data**
"""

import os
import urllib.request

if not os.path.exists("the-verdict.txt"):
  url = ("https://raw.githubusercontent.com/Blackstorm-619/LLM_from_scratch/refs/heads/AD/01_tokenization/the-verdict.txt")
  file_path = "the-verdict.txt"
  urllib.request.urlretrieve(url, file_path)

with open ("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()
print("Total no of characters:", len(raw_text))
print(raw_text[:99])

import re
text = "hello world! This, is: a test."
result = re.split(r'(\s)', text)
print(result)

import re
text = "hello world! This, is: a test."
result = re.split(r'([,.]|\s)', text)
print(result)

import re
text = "hello world! This, is -- a test."
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)